/*
    CodeSamplesTable Component.

    This is a Redux-managed React component that renders a table of code samples from
    GitHub Api. It displays repositories with metadata such as
    engagement metrics, last commit date, languages used, and categories.
 */
import React, { useState } from 'react'
import PropTypes from 'prop-types'
import { useSelector } from 'react-redux'

import { categoryIcon, categoryLabel, ContentCategories } from '../../components/categories/Component'
import Loading from '../../components/Loading'

import './styles.css'

// Used to validate the structure of the public/data/github.json data for each repository
// which itself is generated by the shared/githubDownloader.js script which is run
// weekly on a cron schedule by Github Actions and included in the react build so
// that it can be locally served to Redux.
const repoStateShape = PropTypes.shape({
  name: PropTypes.string.isRequired,
  html_url: PropTypes.string.isRequired,
  private: PropTypes.bool,
  description: PropTypes.string,
  visibility: PropTypes.string,
  forks: PropTypes.number,
  open_issues: PropTypes.number,
  watchers: PropTypes.number,
  stargazers_count: PropTypes.number,
  topics: PropTypes.arrayOf(PropTypes.string),
  categories: PropTypes.arrayOf(PropTypes.string),
  last_commit_date: PropTypes.string,
  total_commits: PropTypes.number,
  languages: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string.isRequired,
      bytes: PropTypes.number,
      percentage: PropTypes.string.isRequired,
    })
  ),
  readme: PropTypes.shape({
    content: PropTypes.string,
    name: PropTypes.string,
    path: PropTypes.string,
    sha: PropTypes.string,
    size: PropTypes.number,
    downloadUrl: PropTypes.string,
    readmeFormat: PropTypes.string,
  }),
  categoryLabels: PropTypes.arrayOf(PropTypes.string),
  categoryIcons: PropTypes.arrayOf(PropTypes.element),
})

// Used to validate the structure of the repositories state in Redux.
const repositoriesStateShape = PropTypes.shape({
  isLoading: PropTypes.bool.isRequired,
  errMess: PropTypes.string,
  repos: PropTypes.arrayOf(repoStateShape.isRequired),
})


// ---------------------------- Internal Components ------------------------------

const CodeEngagement = ({ repo }) => {
  /*
    Renders a table showing the popularity metrics for the given repository.
    Part of repository metadata. Sourced from github.json.
   */
  return (
    <React.Fragment>
      <table className="table-sm m-0 p-0 w-100 text-center small text-muted">
        <thead>
          <tr>
            <th className="w-25 border">⭐</th>
            <th className="w-25 border">🍴</th>
            <th className="w-25 border">👁</th>
            <th className="w-25 border">🐛</th>
          </tr>
        </thead>
        <tbody>
          <tr className="">
            <td className="border">{repo.stargazers_count}</td>
            <td className="border">{repo.forks}</td>
            <td className="border">{repo.watchers}</td>
            <td className="border">{repo.open_issues}</td>
          </tr>
        </tbody>
      </table>
    </React.Fragment>
  )
}
CodeEngagement.propTypes = {
  repo: repoStateShape.isRequired,
}

const CodeCommits = ({ repo }) => {
  /*
    Renders the last commit date and total commits for the given repository.
    Part of repository metadata. Sourced from github.json.
   */
  return (
    <React.Fragment>
      <div className="mt-2">
        <small className="text-muted text-end">
          <div>
            Last commit:{' '}
            {new Date(repo.last_commit_date).toLocaleDateString('en-US', {
              month: 'short',
              year: 'numeric',
            })}
          </div>
          <div>Total commits: {repo.total_commits.toLocaleString()}</div>
        </small>
      </div>
    </React.Fragment>
  )
}

CodeCommits.propTypes = {
  repo: repoStateShape.isRequired,
}

const CodeLanguages = ({ repo }) => {
  /*
    Renders a list of up to 3 programming languages used in the given repository.
    Part of repository metadata. Sourced from github.json.
   */
  return (
    <React.Fragment>
      <div className="mt-2">
        <div className="mb-1 text-end text-muted">
          {(repo.languages || []).slice(0, 3).map((lang) => (
            <div key={lang.name} className="mb-1 text-end">
              <small key={lang.name} className="small">
                {lang.name} ({lang.percentage}%)
              </small>
            </div>
          ))}
        </div>
      </div>
    </React.Fragment>
  )
}

CodeLanguages.propTypes = {
  repo: repoStateShape.isRequired,
}

const CodeMetadata = ({ repo }) => {
  /*
   Top-level component that renders metadata information for the given repository.
   Only shown on medium and larger screens.
   ContentCategories categories={repo.categoryIcons}
   */
  return (
    <React.Fragment>
      <ContentCategories categories={repo.categoryIcons} />
      <CodeEngagement repo={repo} />
      <CodeCommits repo={repo} />
      <hr />
      <CodeLanguages repo={repo} />
    </React.Fragment>
  )
}
CodeMetadata.propTypes = {
  repo: repoStateShape.isRequired,
}

const CodeRepositoryLink = ({ repo }) => {
  /*
   Renders a link to the given repository, with a padlock icon if it's private.
   */
  return (
    <React.Fragment>
      {repo.private && (
        <img
          src="/assets/images/padlock.png"
          alt="Private repository"
          height="16"
          style={{ marginRight: '8px', verticalAlign: 'middle' }}
        />
      )}
      <a href={repo.html_url} target="_blank" rel="noopener noreferrer">
        <strong>{repo.name}</strong>
      </a>
    </React.Fragment>
  )
}
CodeRepositoryLink.propTypes = {
  repo: repoStateShape.isRequired,
}

const CodeDescription = ({ repo }) => {
  /*
    Renders the README content snippet for the given repository, or a placeholder if none exists.
    README filtering logic is handled in shared/githubDownloader.js.
   */
  return (
    <React.Fragment>
      <div
        className="code-sample-readme align-top text-break"
        style={{
          maxHeight: '200px',
          overflowY: 'auto',
          overflowX: 'hidden',
        }}
        dangerouslySetInnerHTML={{
          __html: repo.readme?.content || '<em>No description available</em>',
        }}
      />
    </React.Fragment>
  )
}
CodeDescription.propTypes = {
  repo: repoStateShape.isRequired,
}

const CodeRepository = ({ repo }) => {
  /*
    Top-level component that renders the repository link and description.
   */
  return (
    <React.Fragment>
      <table className="mb-0">
        <tbody>
          <tr>
            <td>
              <CodeRepositoryLink repo={repo} />
            </td>
          </tr>
          <tr>
            <td className="ps-3 pt-3">
              <CodeDescription repo={repo} />
            </td>
          </tr>
        </tbody>
      </table>
    </React.Fragment>
  )
}
CodeRepository.propTypes = {
  repo: repoStateShape.isRequired,
}

// ------------------------------ Main Component ------------------------------

const CodeSamplesTable = ({ category, maxrows=100 }) => {
  /*
   Renders a table of code samples for the given category.
   */
  const [currentMaxRows, setCurrentMaxRows] = useState(maxrows)

  const reduxRepositories = useSelector((state) => state.repositories)
  const reduxSpecialties = useSelector((state) => state.specialties)    // for future use.

  const unfilteredRepositories = [
    ...(category
      ? reduxRepositories.repos.filter((redux) => redux.categories.includes(category))
      : reduxRepositories.repos),
  ]
    .map((repo) => {
      // If category is specified, remove the corresponding entry so that it doesn't
      // redundantly appear in the table.
      if (category && repo.categories) {
        const categoryIndex = repo.categories.indexOf(category)
        if (categoryIndex !== -1) {
          return {
            ...repo,
            categories: repo.categories.filter((_, index) => index !== categoryIndex),
          }
        }
      }
      return repo
    })
    .map((repo) => ({
      ...repo,
      categoryLabels: repo.categories.map(categoryLabel).filter(Boolean),
      categoryIcons: repo.categories
        .map((categoryCode) => categoryIcon(categoryCode, reduxSpecialties))
        .filter(Boolean),
    }))
    .sort((a, b) => {
      // Primary sort: combined engagement score (stargazers + watchers + forks) descending
      const aEngagement = a.stargazers_count + a.watchers + a.forks
      const bEngagement = b.stargazers_count + b.watchers + b.forks
      if (bEngagement !== aEngagement) {
        return bEngagement - aEngagement
      }
      // Secondary sort: total_commits (descending)
      return b.total_commits - a.total_commits
    })

  const unfilteredCount = unfilteredRepositories.length
  const filteredRepositories = unfilteredRepositories.slice(0, currentMaxRows)

  const handleShowMore = () => {
    setCurrentMaxRows(1000)
  }

  return (
    <div className="table-responsive">
      {reduxRepositories.isLoading ? (
        <Loading />
      ) : (
        <React.Fragment>
          <table
            className="table table-bordered table-striped table-fixed mt-4 w-100"
            id="code-samples-table"
          >
            <thead className="thead-dark">
              <tr>
                <th style={{ width: '80%' }}>Repository</th>
                <th className="hide-medium" style={{ width: '20%' }}></th>
              </tr>
            </thead>
            <tbody>
              {filteredRepositories.map((repo) => (
                <tr key={repo.name}>
                  <td className="align-top">
                    <CodeRepository repo={repo} />
                  </td>
                  <td className="hide-medium">
                    <CodeMetadata repo={repo} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {unfilteredCount > currentMaxRows && (
            <div className="text-center mt-3">
              <button
                className="btn btn-primary"
                onClick={handleShowMore}
              >
                More ({unfilteredCount - currentMaxRows} remaining)
              </button>
            </div>
          )}

        </React.Fragment>
      )}
    </div>
  )
}

CodeSamplesTable.propTypes = {
  category: PropTypes.string,
  maxrows: PropTypes.number,
}

export default CodeSamplesTable
export { repoStateShape, repositoriesStateShape }
