/*
    Videos Component.

    This is a Redux-managed React component that renders a table of code samples from
    GitHub Api. It displays repositories with metadata such as
    engagement metrics, last commit date, languages used, and skills.
 */
import React, { useState } from 'react'
import PropTypes from 'prop-types'
import { useSelector } from 'react-redux'
import { skillIcon, skillLabel } from '../Component'
import Loading from '../../Loading'

import './styles.css'

// Used to validate the structure of the public/data/youtube.json data for each
// YouTube video in the Redux store, which itself is generated by the
// shared/fetchers/youtubeFetcher.js script which is run weekly on a cron schedule by
// Github Actions and included in the react build so that it can be locally served to Redux.
const videoStateShape = PropTypes.shape({
  id: PropTypes.string.isRequired,
  title: PropTypes.string.isRequired,
  description: PropTypes.string.isRequired,
  publishedAt: PropTypes.string.isRequired,
  thumbnails: PropTypes.shape({
    default: PropTypes.shape({
      url: PropTypes.string.isRequired,
      width: PropTypes.number.isRequired,
      height: PropTypes.number.isRequired,
    }),
    medium: PropTypes.shape({
      url: PropTypes.string.isRequired,
      width: PropTypes.number.isRequired,
      height: PropTypes.number.isRequired,
    }),
    high: PropTypes.shape({
      url: PropTypes.string.isRequired,
      width: PropTypes.number.isRequired,
      height: PropTypes.number.isRequired,
    }),
    standard: PropTypes.shape({
      url: PropTypes.string.isRequired,
      width: PropTypes.number.isRequired,
      height: PropTypes.number.isRequired,
    }),
    maxres: PropTypes.shape({
      url: PropTypes.string.isRequired,
      width: PropTypes.number.isRequired,
      height: PropTypes.number.isRequired,
    }),
  }).isRequired,
  tags: PropTypes.arrayOf(PropTypes.string).isRequired,
  duration: PropTypes.string.isRequired,
  viewCount: PropTypes.number.isRequired,
  likeCount: PropTypes.number.isRequired,
  commentCount: PropTypes.number.isRequired,
  url: PropTypes.string.isRequired,
  categoryLabels: PropTypes.arrayOf(PropTypes.string),
  categoryIcons: PropTypes.arrayOf(PropTypes.element),
})

// Used to validate the structure of the videos state in Redux.
const videosStateShape = PropTypes.shape({
  isLoading: PropTypes.bool.isRequired,
  errMess: PropTypes.string,
  videos: PropTypes.arrayOf(videoStateShape.isRequired),
})

// ---------------------------- Internal Components ------------------------------

const VideoMetadata = ({ video }) => {
  /*
   Top-level component that renders metadata information for the given repository.
   Only shown on medium and larger screens.
   */

  return (
    <React.Fragment>
      <img
        className="img-fluid"
        src={video.thumbnails.standard.url}
        alt={video.title}
        title={video.title}
        loading="lazy"
      />
    </React.Fragment>
  )
}
VideoMetadata.propTypes = {
  video: videoStateShape.isRequired,
}

const VideoLink = ({ video }) => {
  /*
   Renders a link to the given repository, with a padlock icon if it's private.
   */
  return (
    <React.Fragment>
      <a href={video.url} target="_blank" rel="noopener noreferrer">
        <strong>{video.title}</strong>
      </a>
    </React.Fragment>
  )
}
VideoLink.propTypes = {
  video: videoStateShape.isRequired,
}

const VideoDescription = ({ video }) => {
  /*
    Renders the README content snippet for the given repository, or a placeholder if none exists.
    README filtering logic is handled in shared/githubDownloader.js.
   */
  return (
    <React.Fragment>
      <div
        className="align-top text-break"
        style={{
          maxHeight: '200px',
          overflowY: 'auto',
          overflowX: 'hidden',
        }}
      >
        <p>{video.description}</p>
      </div>
    </React.Fragment>
  )
}
VideoDescription.propTypes = {
  video: videoStateShape.isRequired,
}

const Video = ({ video }) => {
  /*
    Top-level component that renders the repository link and description.
   */
  return (
    <React.Fragment>
      <table className="mb-0">
        <tbody>
          <tr>
            <td>
              <VideoLink video={video} />
            </td>
          </tr>
          <tr>
            <td className="ps-3 pt-3">
              <VideoDescription video={video} />
            </td>
          </tr>
        </tbody>
      </table>
    </React.Fragment>
  )
}
Video.propTypes = {
  video: videoStateShape.isRequired,
}

// ------------------------------ Main Component ------------------------------

const VideosTable = ({ skill, maxrows = 100 }) => {
  /*
   Renders a table of videos and other publications.
   */
  const [currentMaxRows, setCurrentMaxRows] = useState(maxrows)
  const reduxVideos = useSelector((state) => state.videos)
  const reduxSpecialties = useSelector((state) => state.specialties) // for future use.

  const unfilteredVideos = [
    ...(skill
      ? (reduxVideos.videos || []).filter((redux) => (redux.skills || []).includes(skill))
      : reduxVideos.videos || []),
  ]
    .map((video) => {
      let prunedDescription = video.description
      let markerIndex = -1
      if (video.description) {
        markerIndex = video.description.indexOf('THIS VIDEO IS NOT SPONSORED')
        if (markerIndex > 0) {
          prunedDescription = video.description.substring(0, markerIndex).trim()
        }
      }

      return {
        ...video,
        description: prunedDescription,
      }
    })
    .map((video) => {
      // If skill is specified, remove the corresponding entry so that it doesn't
      // redundantly appear in the table.
      if (skill && video.skills) {
        const skillIndex = video.skills.indexOf(skill)
        if (skillIndex !== -1) {
          return {
            ...video,
            skills: video.skills.filter((_, index) => index !== skillIndex),
          }
        }
      }
      return video
    })
    .map((video) => ({
      ...video,
      categoryLabels: (video.skills || []).map(skillLabel).filter(Boolean),
      categoryIcons: (video.skills || [])
        .map((categoryCode) => skillIcon(categoryCode, reduxSpecialties))
        .filter(Boolean),
    }))
    .sort((a, b) => {
      const scoreA = a.viewCount + a.likeCount + 5 + a.commentCount * 10
      const scoreB = b.viewCount + b.likeCount + 5 + b.commentCount * 10
      return scoreB - scoreA
    })

  const unfilteredCount = unfilteredVideos.length
  const filteredVideos = unfilteredVideos.slice(0, currentMaxRows)

  const handleShowMore = () => {
    setCurrentMaxRows(1000)
  }

  return (
    <div className="table-responsive">
      {reduxVideos.isLoading ? (
        <Loading />
      ) : (
        <React.Fragment>
          <table
            className="table table-bordered table-striped table-fixed mt-1 w-100"
            id="videos-table"
          >
            <thead className="thead-dark">
              <tr>
                <th style={{ width: '80%' }}>Video</th>
                <th className="hide-medium" style={{ width: '20%' }}></th>
              </tr>
            </thead>
            <tbody>
              {filteredVideos.map((video) => (
                <tr key={video.id}>
                  <td className="align-top">
                    <Video video={video} />
                  </td>
                  <td className="hide-medium p-0 m-0">
                    <VideoMetadata video={video} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {unfilteredCount > currentMaxRows && (
            <div className="text-center mt-3">
              <button className="btn btn-primary" onClick={handleShowMore}>
                More ({unfilteredCount - currentMaxRows} remaining)
              </button>
            </div>
          )}
        </React.Fragment>
      )}
    </div>
  )
}

VideosTable.propTypes = {
  skill: PropTypes.string,
  maxrows: PropTypes.number,
}

export default VideosTable
export { videoStateShape, videosStateShape }
